# Generated by Django 3.2.8 on 2021-11-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_servicio_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='update',
            new_name='updated',
        ),
    ]
